import { db } from './firebase';
import { collection, doc, writeBatch } from 'firebase/firestore';

const MOCK_PRODUCTS = [
  {
    name: 'Hybrid Paddy Seeds (PR-126)',
    category: 'seeds',
    price: 480,
    unit: '5kg bag',
    rating: 4.8,
    stock: 150,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?q=80&w=800&auto=format&fit=crop',
    isOrganic: false,
    description: 'High-yield hybrid paddy seeds suitable for kharif season. Resistant to blast disease and stem borer. Produces 35-40 quintals per acre under good management.',
    benefits: ['High Yield', 'Disease Resistant', 'Short Duration (125 days)'],
    deliveryCharge: 0
  },
  {
    name: 'NPK Granular Fertilizer (19:19:19)',
    category: 'fertilizers',
    price: 1350,
    unit: '50kg bag',
    rating: 4.7,
    stock: 200,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?q=80&w=800&auto=format&fit=crop',
    isOrganic: false,
    description: 'Balanced NPK water-soluble granular fertilizer in 19:19:19 ratio. Ideal for all crops at the vegetative growth stage. Promotes root development and uniform crop growth.',
    benefits: ['Balanced Nutrition', 'Water Soluble', 'Boosts Root Growth'],
    deliveryCharge: 50
  },
  {
    name: 'Neem Oil Bio-Pesticide Spray',
    category: 'pesticides',
    price: 320,
    unit: '1 litre',
    rating: 4.9,
    stock: 80,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1585664811087-47f65abbad64?q=80&w=800&auto=format&fit=crop',
    isOrganic: true,
    description: 'Cold-pressed pure neem oil (Azadirachtin 3000ppm). Effective against aphids, whiteflies, mites, and fungal diseases. Safe for bees and beneficial insects when used as directed.',
    benefits: ['100% Organic', 'Broad Spectrum', 'Safe for Pollinators'],
    deliveryCharge: 0
  },
  {
    name: 'Battery-Powered Knapsack Sprayer (16L)',
    category: 'machinery',
    price: 2850,
    unit: '1 unit',
    rating: 4.6,
    stock: 40,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=800&auto=format&fit=crop',
    isOrganic: false,
    description: '16-litre rechargeable battery knapsack sprayer with adjustable nozzle. 12V lithium battery with 6-8 hour run time. Perfect for pesticide and fertilizer application across all field sizes.',
    benefits: ['Rechargeable Battery', '6-8 Hour Runtime', 'Adjustable Spray Nozzle'],
    deliveryCharge: 100
  },
  {
    name: 'Premium Basmati Rice',
    category: 'grains',
    price: 120,
    unit: '1kg',
    rating: 4.9,
    stock: 500,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?q=80&w=800&auto=format&fit=crop',
    isOrganic: true,
    description: 'Traditional long-grain Basmati rice, aged to perfection. Naturally grown and processed with minimal intervention.',
    benefits: ['Aged', 'Natural', 'Non-GMO'],
    deliveryCharge: 0
  },
  {
    name: 'Vermicompost Organic Manure',
    category: 'fertilizers',
    price: 280,
    unit: '25kg bag',
    rating: 5.0,
    stock: 300,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1603912699214-92627f304eb6?q=80&w=800&auto=format&fit=crop',
    isOrganic: true,
    description: 'Premium quality vermicompost prepared from organic cow dung and crop residues. Rich in humus, macro and micro nutrients. Improves soil structure, water retention and beneficial microbial activity.',
    benefits: ['100% Organic', 'Improves Soil Health', 'Slow Release Nutrients'],
    deliveryCharge: 0
  },
  {
    name: 'Pure Desi Cow Ghee (A2)',
    category: 'cattle',
    price: 1250,
    unit: '1 litre',
    rating: 5.0,
    stock: 100,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1603401569434-8be080470557?q=80&w=800&auto=format&fit=crop',
    isOrganic: true,
    description: 'Authentic A2 Desi Cow Ghee made using the traditional Bilona method. High nutritional value and medicinal properties.',
    benefits: ['Bilona Method', 'A2 Protein', 'Boosts Immunity'],
    deliveryCharge: 0
  },
  {
    name: 'Organic Farm Fresh Tomatoes',
    category: 'fresh',
    price: 45,
    unit: '1kg',
    rating: 4.7,
    stock: 200,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?q=80&w=800&auto=format&fit=crop',
    isOrganic: true,
    description: 'Juicy, farm-fresh organic tomatoes grown without synthetic pesticides. Rich in Lycopene and vitamin C.',
    benefits: ['Chemical Free', 'Farm Fresh', 'High Nutrition'],
    deliveryCharge: 20
  },
  {
    name: 'Gau Ark (Distilled Cow Urine)',
    category: 'cattle',
    price: 150,
    unit: '500ml',
    rating: 4.8,
    stock: 150,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1595079676339-1534801ad6cf?q=80&w=800&auto=format&fit=crop',
    isOrganic: true,
    description: 'Purified and distilled cow urine (Ark). Known for its detoxification and healing properties in traditional Ayurveda.',
    benefits: ['Detoxification', 'Natural Healer', 'Ancient Formula'],
    deliveryCharge: 0
  },
  {
    name: 'Organic Turmeric Finger',
    category: 'fresh',
    price: 220,
    unit: '1kg',
    rating: 4.9,
    stock: 300,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?q=80&w=800&auto=format&fit=crop',
    isOrganic: true,
    description: 'High-curcumin organic turmeric fingers. Directly sourced from farmers following traditional organic methods.',
    benefits: ['High Curcumin', 'Natural Antiseptic', 'Direct from Farm'],
    deliveryCharge: 0
  },
  {
    name: 'Manual Seed Drill (Single Row)',
    category: 'machinery',
    price: 4500,
    unit: '1 unit',
    rating: 4.5,
    stock: 25,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1589923188900-85dae523342b?q=80&w=800&auto=format&fit=crop',
    isOrganic: false,
    description: 'Adjustable manual seed drill for uniform sowing of various seeds like wheat, mustard, and pulses. Improves labor efficiency.',
    benefits: ['Uniform Sowing', 'Labor Saving', 'Easy to Use'],
    deliveryCharge: 200
  },
  {
    name: 'Cow Dung Cake (Upla)',
    category: 'cattle',
    price: 120,
    unit: '24 pieces',
    rating: 4.9,
    stock: 500,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1590483734724-383b85376532?q=80&w=800&auto=format&fit=crop',
    isOrganic: true,
    description: 'Sun-dried cow dung cakes made from indigenous cow dung. Ideal for havan, cooking, and as organic manure.',
    benefits: ['Smoke Free', 'Natural Fuel', 'Rich Manure Source'],
    deliveryCharge: 30
  },
  {
    name: 'Hybrid Mustard Seeds (Varuna)',
    category: 'seeds',
    price: 420,
    unit: '2kg pack',
    rating: 4.7,
    stock: 180,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1600122971206-886981882103?q=80&w=800&auto=format&fit=crop',
    isOrganic: false,
    description: 'High-yield hybrid mustard seeds. Resistant to white rust and powdery mildew. Oil content approx 40-42%.',
    benefits: ['High Oil Content', 'Disease Resistant', 'Fast Maturity'],
    deliveryCharge: 0
  },
  {
    name: 'Organic Black Gram (Urad)',
    category: 'grains',
    price: 160,
    unit: '1kg pack',
    rating: 4.8,
    stock: 250,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1585914924626-45adac9e6b42?q=80&w=800&auto=format&fit=crop',
    isOrganic: true,
    description: 'Unpolished organic black gram. Rich in protein and iron. Grown using natural fertilizers in the Bundelkhand region.',
    benefits: ['High Protein', 'Unpolished', 'Naturally Grown'],
    deliveryCharge: 0
  },
  {
    name: 'Bio-Fertilizer (Azotobacter)',
    category: 'fertilizers',
    price: 180,
    unit: '500ml',
    rating: 4.6,
    stock: 150,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1628352081506-83c43123ed6d?q=80&w=800&auto=format&fit=crop',
    isOrganic: true,
    description: 'Bacterial bio-fertilizer that fixes atmospheric nitrogen in the soil. Enhances seed germination and plant growth.',
    benefits: ['Nitrogen Fixing', 'Eco Friendly', 'Cost Effective'],
    deliveryCharge: 0
  },
  {
    name: 'Electric Grass Cutter',
    category: 'machinery',
    price: 12500,
    unit: '1 unit',
    rating: 4.4,
    stock: 10,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1592150621344-82d67bdb79ad?q=80&w=800&auto=format&fit=crop',
    isOrganic: false,
    description: 'Powerful 1500W electric grass cutter for maintaining fodder and lawns. Adjustable height settings and safety guard.',
    benefits: ['Powerful Motor', 'Easy Storage', 'Safe Operation'],
    deliveryCharge: 300
  },
  {
    name: 'Wheat Seeds (Sonalika)',
    category: 'seeds',
    price: 550,
    unit: '40kg bag',
    rating: 4.7,
    stock: 250,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?q=80&w=800&auto=format&fit=crop',
    isOrganic: false,
    description: 'High-quality Sonalika wheat seeds. Excellent yield and resistant to common pests.',
    benefits: ['High Yield', 'Rust Resistant', 'Fast Growth'],
    deliveryCharge: 0
  },
  {
    name: 'Urea (Nitrogen Fertilizer)',
    category: 'fertilizers',
    price: 300,
    unit: '45kg bag',
    rating: 4.5,
    stock: 400,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?q=80&w=800&auto=format&fit=crop',
    isOrganic: false,
    description: 'Highly effective nitrogenous fertilizer. Essential for leafy growth and lush green color.',
    benefits: ['High Nitrogen', 'Affordable', 'Quick Acting'],
    deliveryCharge: 50
  },
  {
    name: 'Mini Power Tiller (3HP)',
    category: 'machinery',
    price: 18500,
    unit: '1 unit',
    rating: 4.8,
    stock: 15,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1595113316349-9fa4ee24f884?q=80&w=800&auto=format&fit=crop',
    isOrganic: false,
    description: 'Compact and powerful 3HP petrol engine power tiller. Ideal for inter-cultivation and weeding in small farms, orchards, and vegetable gardens.',
    benefits: ['Compact Design', 'Powerful Engine', 'Easy to Maneuver'],
    deliveryCharge: 500
  },
  {
    name: 'Organic Moong Dal (Whole)',
    category: 'grains',
    price: 180,
    unit: '1kg pack',
    rating: 4.9,
    stock: 400,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1585914924626-45adac9e6b42?q=80&w=800&auto=format&fit=crop',
    isOrganic: true,
    description: 'Pure organic whole moong dal. High in protein and fiber. Naturally grown without chemical fertilizers.',
    benefits: ['High Protein', 'Chemical Free', 'Easy to Digest'],
    deliveryCharge: 0
  },
  {
    name: 'Bt Cotton Seeds (Hybrid)',
    category: 'seeds',
    price: 860,
    unit: '450g pack',
    rating: 4.7,
    stock: 100,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1594903582424-8146449a7a11?q=80&w=800&auto=format&fit=crop',
    isOrganic: false,
    description: 'Bollgard II technology Bt cotton seeds. Excellent resistance to American Bollworm and other pests. High boll weight and superior fiber quality.',
    benefits: ['Pest Resistant', 'High Boll Weight', 'Quality Fiber'],
    deliveryCharge: 50
  },
  {
    name: 'DAP Fertilizer (Di-Ammonium Phosphate)',
    category: 'fertilizers',
    price: 1350,
    unit: '50kg bag',
    rating: 4.8,
    stock: 150,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1628352081506-83c43123ed6d?q=80&w=800&auto=format&fit=crop',
    isOrganic: false,
    description: 'Essential source of Phosphorus and Nitrogen for all crops. Recommended for basal application to ensure strong root development and early plant growth.',
    benefits: ['High Phosphorus', 'Basal Application', 'Root Growth Boost'],
    deliveryCharge: 100
  },
  {
    name: 'Trichoderma Viride Bio-Fungicide',
    category: 'pesticides',
    price: 240,
    unit: '500g pack',
    rating: 4.9,
    stock: 120,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1585664811087-47f65abbad64?q=80&w=800&auto=format&fit=crop',
    isOrganic: true,
    description: 'Natural bio-fungicide that controls soil-borne diseases like root rot, wilt, and damping-off. Improves soil health and enhances crop resistance to pathogens.',
    benefits: ['Bio-Control', 'Eco-Friendly', 'Soil Health'],
    deliveryCharge: 0
  },
  {
    name: 'Solar Water Pump (5HP)',
    category: 'machinery',
    price: 45000,
    unit: '1 set',
    rating: 4.9,
    stock: 10,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb773b09?q=80&w=800&auto=format&fit=crop',
    isOrganic: false,
    description: 'Efficient 5HP solar water pump system with panels and controller. Zero running cost and eco-friendly irrigation solution.',
    benefits: ['Zero Running Cost', 'Eco-Friendly', 'Low Maintenance'],
    deliveryCharge: 1000
  },
  {
    name: 'Organic Pearl Millet (Bajra)',
    category: 'grains',
    price: 65,
    unit: '1kg pack',
    rating: 4.7,
    stock: 600,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?q=80&w=800&auto=format&fit=crop',
    isOrganic: true,
    description: 'Nutrient-dense organic Bajra (Pearl Millet). Gluten-free and rich in iron and magnesium. Traditionally grown in arid regions with no chemical inputs.',
    benefits: ['Gluten Free', 'Rich in Iron', '100% Organic'],
    deliveryCharge: 0
  },
  {
    name: 'Cattle Feed (High Protein)',
    category: 'cattle',
    price: 1850,
    unit: '50kg bag',
    rating: 4.6,
    stock: 200,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?q=80&w=800&auto=format&fit=crop',
    isOrganic: false,
    description: 'Scientifically formulated cattle feed for high milk yield and animal health. Contains balanced minerals and vitamins.',
    benefits: ['High Milk Yield', 'Balanced Nutrition', 'Easy Digestion'],
    deliveryCharge: 100
  },
  {
    name: 'Farm Fresh Organic Potatoes',
    category: 'fresh',
    price: 35,
    unit: '1kg',
    rating: 4.8,
    stock: 500,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=800&auto=format&fit=crop',
    isOrganic: true,
    description: 'Soil-grown organic potatoes, harvested fresh. No synthetic fertilizers used.',
    benefits: ['Fresh Harvest', 'Chemical Free', 'Great Taste'],
    deliveryCharge: 10
  },
  {
    name: 'Drip Irrigation Kit (1 Acre)',
    category: 'machinery',
    price: 12500,
    unit: '1 set',
    rating: 4.9,
    stock: 5,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?q=80&w=800&auto=format&fit=crop',
    isOrganic: false,
    description: 'Complete drip irrigation kit for 1 acre land. Includes main pipe, laterals, drippers, and connectors. Efficient water management for fruit crops and vegetables.',
    benefits: ['Water Saving', 'Uniform Irrigation', 'Easy Installation'],
    deliveryCharge: 500
  },
  {
    name: 'Organic Vermiwash Liquid',
    category: 'fertilizers',
    price: 350,
    unit: '5 litre',
    rating: 4.8,
    stock: 120,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1628352081506-83c43123ed6d?q=80&w=800&auto=format&fit=crop',
    isOrganic: true,
    description: 'Liquid fertilizer collected from vermicompost beds. Rich in enzymes, hormones, and micronutrients. Acts as a natural growth promoter and bio-pesticide.',
    benefits: ['Growth Promoter', 'Organic Certified', 'Rich in Nutrients'],
    deliveryCharge: 40
  },
  {
    name: 'Green Moong Seeds (Summer Special)',
    category: 'seeds',
    price: 180,
    unit: '1kg pack',
    rating: 4.7,
    stock: 200,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1585914924626-45adac9e6b42?q=80&w=800&auto=format&fit=crop',
    isOrganic: true,
    description: 'Short duration green moong seeds, ideal for summer cultivation. High protein content and drought resistant.',
    benefits: ['60 Day Duration', 'High Protein', 'Drought Resistant'],
    deliveryCharge: 0
  },
  {
    name: 'Wheat Grain (Premium Sharbati)',
    category: 'grains',
    price: 45,
    unit: '1kg',
    rating: 4.9,
    stock: 1000,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?q=80&w=800&auto=format&fit=crop',
    isOrganic: true,
    description: 'Premium Sharbati wheat grains, known for their golden texture and sweet taste. Rich in fiber and essential nutrients.',
    benefits: ['Sweet Taste', 'High Fiber', 'Golden Texture'],
    deliveryCharge: 0
  },
  {
    name: 'Potash Fertilizer (MOP)',
    category: 'fertilizers',
    price: 950,
    unit: '50kg bag',
    rating: 4.6,
    stock: 120,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1628352081506-83c43123ed6d?q=80&w=800&auto=format&fit=crop',
    isOrganic: false,
    description: 'Muriate of Potash (MOP) fertilizer. Essential for improving crop quality, disease resistance, and water retention.',
    benefits: ['Quality Booster', 'Disease Resistance', 'Water Retention'],
    deliveryCharge: 80
  },
  {
    name: 'Manual Knapsack Sprayer (20L)',
    category: 'machinery',
    price: 1850,
    unit: '1 unit',
    rating: 4.5,
    stock: 60,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=800&auto=format&fit=crop',
    isOrganic: false,
    description: 'Durable 20-litre manual knapsack sprayer. Ergonomic design for comfortable use. Comes with multiple nozzle types.',
    benefits: ['Large Capacity', 'Ergonomic Design', 'Multiple Nozzles'],
    deliveryCharge: 150
  },
  {
    name: 'Sunflower Seeds (Hybrid)',
    category: 'seeds',
    price: 750,
    unit: '1kg pack',
    rating: 4.8,
    stock: 100,
    status: 'approved',
    sellerId: 'admin',
    sellerName: 'Kishan Seva Store',
    image: 'https://images.unsplash.com/photo-1597848212624-a19eb35e2651?q=80&w=800&auto=format&fit=crop',
    isOrganic: false,
    description: 'High-oil content hybrid sunflower seeds. Suitable for all seasons with good irrigation.',
    benefits: ['High Oil Yield', 'All Season', 'Drought Tolerant'],
    deliveryCharge: 0
  }
];

export async function seedProducts() {
  const batch = writeBatch(db);
  const productsRef = collection(db, 'products');

  MOCK_PRODUCTS.forEach((product) => {
    const newDocRef = doc(productsRef);
    batch.set(newDocRef, {
      ...product,
      createdAt: new Date().toISOString()
    });
  });

  await batch.commit();
  console.log('Database seeded successfully with agricultural products!');
}
